### ISSUE TITLE
Undefinied reference error in lib/sgxdnn.so

### ISSUE THREAD

**Issue by DRyan1995** [ftramer/slalom#29]
After fixing the compilation errors per the instructions in issue #27, the python script is finally running, however, I'm getting undefined symbol error:

`Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/yecheng/repo/slalom/python/slalom/scripts/eval.py", line 225, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/yecheng/repo/slalom/python/slalom/scripts/eval.py", line 80, in main
    sgxutils = SGXDNNUtils(args.use_sgx)
  File "python/slalom/sgxdnn.py", line 37, in __init__
    self.lib = cdll.LoadLibrary(DNNLIB)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 444, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: lib/sgxdnn.so: undefined symbol: sgx_thread_self`

I've tried the same building procedure on both Ubuntu 18.04 and 16.04 but the error remains the same.

Could anyone please help on this?

**Comment by ftramer** [comment]
Do you have the SGX SDK and driver installed? This seems to be an error with the SGX-specific headers not being found.

**Comment by DRyan1995** [comment]
Thank you for replying, I was suspecting on that too.
However I have installed SGX SDK and driver (I could run the sample code provided by Intel w/o error). I also set the `LD_LIBRARY_PATH` to the SDK include (header) folder. It seems a linking error but I could not find any other clues.

**Comment by DRyan1995** [comment]
I redownloaded the Eigen lib from github and recompiled it, and it's now working, thank you @ftramer for your fast response!
