### ISSUE TITLE
undefined symbol: cudaGetDeviceCount

### ISSUE THREAD

**Issue by gutouyu** [ftramer/slalom#3]
After build the slalom following the readme, I run this:
```
python -m python.slalom.scripts.eval mobilenet sgxdnn --batch_size=2 --max_num_batches=2
```
so sad, I still got an error:
```
Using TensorFlow backend.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ninglee/sgx/slalom/python/slalom/scripts/eval.py", line 16, in <module>
    from python.slalom.quant_layers import transform
  File "python/slalom/quant_layers.py", line 15, in <module>
    fmod_module = tf.load_op_library('./App/cuda_fmod.so')
  File "/home/ninglee/.local/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: ./App/cuda_fmod.so: undefined symbol: cudaGetDeviceCount
```

I have no idea why this is happening, as I did everything readme told to. Looking forward to hear from you. Thanks very much.

**Comment by gutouyu** [comment]
this is because I install tensorflow and tensorflow-gpu, also I'm using gcc5.x,so I have to add flags `-D_GLIBCXX_USE_CXX11_ABI=0` as well as uninstall tensorflow, only remain tensorflow-gpu

**Comment by ohsai** [comment]
So you mean you removed tensorflow 1.8.0 which was in requirement.txt? Also, where should we place ´´´-D_GLIBCXX_USE_CXX11_ABI=0´´´ at?
