### ISSUE TITLE
lib/slalom_ops.so: undefined symbol

### ISSUE THREAD

**Issue by HuiliChen** [ftramer/slalom#7]
Dear Author,

After installing everything and we inference mobilenet by using the following command:
`python -m python.slalom.scripts.eval mobilenet sgxdnn --batch_size=2 --max_num_batches=2`

And the slalom.so reports that the code has an undefined symbol:

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/huili/Desktop/slalom/python/slalom/scripts/eval.py", line 199, in <module>
    tf.app.run()
  File "/home/huili/venv_test/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/huili/Desktop/slalom/python/slalom/scripts/eval.py", line 76, in main
    sgxutils = SGXDNNUtils(args.use_sgx)
  File "/home/huili/Desktop/slalom/python/slalom/sgxdnn.py", line 37, in __init__
    self.slalom_lib = tf.load_op_library(SLALOM_LIB)
  File "/home/huili/venv_test/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: lib/slalom_ops.so: undefined symbol: _ZN10tensorflow16FormatFromStringERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS_12TensorFormatE

```
Under sgx mode, the same problem arised for lib/slalom_ops_sgx.so:

`tensorflow.python.framework.errors_impl.NotFoundError: lib/slalom_ops_sgx.so: undefined symbol: _ZN10tensorflow16FormatFromStringERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS_12TensorFormatE
`
G++ version on my computer is 5.4.0 and I used tensorflow 1.8 with GPU support cuda 9.0 + cudnn 7.1.
Do you have any idea about this problem?  Any suggestion would be highly appreciated.

**Comment by gutouyu** [comment]
You need to modify `App/Makefile`, uncomment 13th line : 
`App_Link_Flags += -ltensorflow_framework -D_GLIBCXX_USE_CXX11_ABI=0`
and it will solve this problem.

It's because you are using g++ 5.x.  Glad to help you.
